on:
  push:
  schedule:
    - cron: '42 * * * *'


jobs:
  check_updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py ${{ secrets.DISCORD_WEBHOOK }} melanx.txt
          python main.py ${{ secrets.DISCORD_WEBHOOK_2 }} noeppi.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update last_checked.json
          file_pattern: last_checked.json
